jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: mvn --no-transfer-progress verify source:jar javadoc:jar
    - continue-on-error: true
      if: ${{ github.ref == 'refs/heads/master' && github.repository == 'square/javapoet'
        }}
      run: mvn --no-transfer-progress deploy --settings=".github/workflows/settings.xml"
        -Dmaven.test.skip=true
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
